# Generated by Django 3.2.6 on 2021-08-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=60)),
                ('customer_address', models.CharField(default='No Record', max_length=255)),
                ('contact_person', models.CharField(default='No Record', max_length=30)),
                ('designation', models.CharField(default='No Record', max_length=30)),
                ('email', models.CharField(default='No Record', max_length=40)),
                ('phone', models.CharField(default='No Record', max_length=20)),
            ],
            options={
                'ordering': ('customer',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_city', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Cities',
                'ordering': ('customer_city',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Status of Deliveries',
                'ordering': ('delivery_status',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Employee Names',
                'ordering': ('employee_name',),
            },
        ),
        migrations.CreateModel(
            name='GeneralExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_expense_category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories - General',
                'ordering': ('general_expense_category',),
            },
        ),
        migrations.CreateModel(
            name='GeneralExpenseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_mode', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Expense Modes - General',
                'ordering': ('expense_mode',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ref', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('value', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_details', models.CharField(blank=True, max_length=255, null=True)),
                ('order_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customer')),
                ('customer_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_city', to='accounts.customercity')),
                ('delivery_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_delivery_status', to='accounts.deliverystatus')),
            ],
            options={
                'ordering': ('-order_ref',),
            },
        ),
        migrations.CreateModel(
            name='OrderExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_expense_category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories - Orders',
                'ordering': ('order_expense_category',),
            },
        ),
        migrations.CreateModel(
            name='OrderExpenseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_expense_mode', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Expense Modes - Orders',
                'ordering': ('order_expense_mode',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Received Payment Modes',
                'ordering': ('payment_mode',),
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Status of Payments',
                'ordering': ('payment_status',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Terms of Payment',
                'ordering': ('payment_terms',),
            },
        ),
        migrations.CreateModel(
            name='VendorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_city', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Vendor Cities',
                'ordering': ('vendor_city',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=60)),
                ('vendor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(default='No Record', max_length=60)),
                ('designation', models.CharField(default='No Record', max_length=30)),
                ('email', models.CharField(default='No Record', max_length=30)),
                ('phone', models.CharField(default='No Record', max_length=15)),
                ('products_or_services', models.CharField(blank=True, max_length=255, null=True)),
                ('notes_or_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='accounts.vendorcity')),
            ],
            options={
                'ordering': ('vendor',),
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received_date', models.DateField()),
                ('received_amount', models.FloatField(default=0.0)),
                ('invoice_ref', models.CharField(blank=True, max_length=15, null=True)),
                ('notes_or_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_by', to='accounts.customer')),
                ('order_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.order')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receive_mode', to='accounts.paymentmode')),
            ],
            options={
                'verbose_name_plural': 'Received Payments',
                'ordering': ('-payment_received_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('expense_amount', models.FloatField(default=0.0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes_or_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_expense_category', to='accounts.orderexpensecategory')),
                ('expense_made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_by', to='accounts.employeename')),
                ('expense_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_expense_mode', to='accounts.orderexpensemode')),
                ('order_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.order')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_to', to='accounts.vendor')),
            ],
            options={
                'verbose_name_plural': 'Expenses - Orders',
                'ordering': ('-expense_date',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_payment_status', to='accounts.paymentstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_payment_terms', to='accounts.paymentterm'),
        ),
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('expense_amount', models.FloatField(default=0.0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes_or_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gen_expense_category', to='accounts.generalexpensecategory')),
                ('expense_made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spent_by', to='accounts.employeename')),
                ('expense_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_expense_mode', to='accounts.generalexpensemode')),
            ],
            options={
                'verbose_name_plural': 'Expenses - General',
                'ordering': ('-expense_date',),
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.customercity'),
        ),
    ]
